# Generated by Django 5.1.7 on 2025-03-21 21:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('ref', models.CharField(editable=False, max_length=250, null=True, unique=True)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
